package com.example.demo.model;

public class RoleResourcesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resources.roleId
     *
     * @mbggenerated Fri Feb 23 14:04:56 CST 2018
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resources.resourcesId
     *
     * @mbggenerated Fri Feb 23 14:04:56 CST 2018
     */
    private Integer resourcesid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resources.roleId
     *
     * @return the value of role_resources.roleId
     *
     * @mbggenerated Fri Feb 23 14:04:56 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resources.roleId
     *
     * @param roleid the value for role_resources.roleId
     *
     * @mbggenerated Fri Feb 23 14:04:56 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resources.resourcesId
     *
     * @return the value of role_resources.resourcesId
     *
     * @mbggenerated Fri Feb 23 14:04:56 CST 2018
     */
    public Integer getResourcesid() {
        return resourcesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resources.resourcesId
     *
     * @param resourcesid the value for role_resources.resourcesId
     *
     * @mbggenerated Fri Feb 23 14:04:56 CST 2018
     */
    public void setResourcesid(Integer resourcesid) {
        this.resourcesid = resourcesid;
    }
}